#!/usr/bin/env python
""" 
Space-separated fields => tab separated.  very tolerant of inconsistent
numbers of spaces.  Examples:

uniq -c | ssv2tsv
echo id name count | ssv2tsv

This really should be called 'ssv2tab' or 'space2tab' to be more in-line with
the naming conventions elsewhere, but I personally find those names harder to
remember.
"""
import sys
import tsvutil
tsvutil.fix_stdio()

for line in sys.stdin:
  print "\t".join([tsvutil.cell_text_clean(x) for x in line.split()])
