#!/usr/bin/env ruby
$doc = %{
tabawk [same args as awk]

Wrapper around 'awk' for tab-separation for both input and output records
}
if ARGV.size==0 #and STDIN.tty?
  STDERR.puts $doc.strip
  exit 1
end

awk_args = ARGV.clone
awk_cmd = ENV["AWK"] || "awk"
cmd = [awk_cmd, "-F\t", "-v", "OFS=\\t"] + awk_args
exec *cmd

