#!/usr/bin/env python
import csv,sys

def tsv_reader(f):
  #return csv.DictReader(f, dialect=None,delimiter="\t",quoting=csv.QUOTE_NONE)
  return csv.reader(f, dialect=None,delimiter="\t",quoting=csv.QUOTE_NONE)

w = csv.writer(sys.stdout)  # encoding issue
for row in tsv_reader(sys.stdin):
  w.writerow(row)


