#!/usr/bin/env python
"""
Wrapper around tabawk, supplying column names as integers for their
corresponding column numbers, so you can do things like

tsvawk '{print $id,$name}'

Your awk script will *not* see the header line from the file.
"""

import sys,os
if sys.stdin.isatty():
  print>>sys.stderr, __doc__.strip()
  sys.exit(1)
sys.stdin = open('/dev/stdin','U',buffering=0)
sys.stdout = open('/dev/stdout','w',buffering=0)
header = sys.stdin.readline()
colnames = header[:-1].split("\t")
flags = []
for i,colname in enumerate(colnames):
  flags += ["-v", "%s=%s" % (colname, i+1)]

#print flags
args = ["tabawk"] + flags + sys.argv[1:]
os.execvp( "tabawk", args )
